logging:
  level:
    root: info
    metrics: info
    performance: ${PERFORMANCE_LOG_LEVEL:info}
    org.springframework.web: info

spring:
  main:
    banner-mode: off
  application:
    name: @project.artifactId@
  cache:
    type: none

server:
  address: ${SERVER_HOST:localhost}
  port: ${SERVER_PORT:30012}
#  tomcat:
#    threads:
#      max: ${TOMCAT_THREADS_MAX:1}
#    max-swallow-size: ${TOMCAT_MAX_SWALLOW_SIZE:10MB}
#    max-http-form-post-size: ${TOMCAT_MAX_HTTP_FORM_POST_SIZE:10MB}
  shutdown: graceful

application:
  master-host: http://${MASTER_HOST:localhost:8080}
  master-health-interval: ${MASTER_HEALTH_INTERVAL:1000}
  master-health-timeout: ${MASTER-HEALTH_TIMEOUT:20000}