logging:
  level:
    root: info
    metrics: info
    performance: ${PERFORMANCE_LOG_LEVEL:info}
    org.springframework.web: info

spring:
  main:
    banner-mode: off
  application:
    name: @project.artifactId@
  cache:
    type: none

  jmx:
    enabled: false

server:
  address: ${SERVER_HOST:localhost}
  port: ${SERVER_PORT:30010}
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:1}
    max-swallow-size: ${TOMCAT_MAX_SWALLOW_SIZE:10MB}
    max-http-form-post-size: ${TOMCAT_MAX_HTTP_FORM_POST_SIZE:10MB}
  shutdown: graceful


info:
  app:
    name: @project.artifactId@
    version: @project.version@

application:
  master-host: http://${MASTER_HOST:localhost:9000}
  master-health-interval: ${MASTER_HEALTH_INTERVAL:1000}


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "health,metrics,loggers,prometheus,env,info,threaddump,heapdump,startup"
  health:
    defaults:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  group-configs:
    - group: web
      paths-to-match:
        - "/api/web/**"
    - group: inner
      paths-to-exclude:
        - "/api/web/**"